# catppuccin mocha theme
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[keyboard]
bindings= [
    # enable ctrl + backspace
    {key="Back", mods="Control", chars="\u0017"},
]
