-- [[ molten.nvim ]]
-- desc: a neovim plugin for interactively running code with the jupyter kernel (fork of magma.nvim)
-- repo: https://github.com/benlubas/molten-nvim

return {}
-- return {
--   "benlubas/molten-nvim",
--   version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
--   dependencies = { "3rd/image.nvim" },
--   build = ":UpdateRemotePlugins",
--   keys = {
--     { "<leader>me", ":MoltenEvaluateOperator<CR>",      { desc = "evaluate operator", silten = true } },
--     { "<leader>mo", ":noautocmd MoltenEnterOutput<CR>", { desc = "open output windows", silten = true } },
--   },
--   init = function()
--     -- these are examples, not defaults. Please see the readme
--     vim.g.molten_image_provider = "image.nvim"
--     vim.g.molten_output_win_max_height = 20
--
--     vim.g.molten_wrap_output = true
--     vim.g.molten_virt_text_output = true
--     vim.g.molten_virt_lines_off_by_1 = true
--   end,
-- }
